--drop TABLE sakdagu_category;
CREATE TABLE sakdagu_category (
	category VARCHAR2(15) not null
	,sub_category VARCHAR2(25)
);

INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('여성의류', '상의');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('여성의류', '하의');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('여성의류', '원피스/세트');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('여성의류', '아우터');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('여성의류', '언더웨어');

INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('남성의류', '상의');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('남성의류', '하의');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('남성의류', '정장/세트');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('남성의류', '아우터');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('남성의류', '언더웨어');

INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('패션잡화', '여성신발');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('패션잡화', '남성신발');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('패션잡화', '운동화/캐쥬얼');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('패션잡화', '가방/지갑');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('패션잡화', '소품/선글라스');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('패션잡화', '시계/쥬얼리');

INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('뷰티', '기초/기능성케어');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('뷰티', '메이크업/클렌징');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('뷰티', '헤어/바디');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('뷰티', '향수/미용');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('뷰티', '남성화장품');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('뷰티', '네일케어');

INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('스포츠패션', '스포츠의류');
INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY, SUB_CATEGORY) VALUES
('스포츠패션', '스포츠슈즈');

INSERT INTO "SKU"."SAKDAGU_CATEGORY" (CATEGORY) VALUES ('해외배송');

commit;
select * from sakdagu_category;

----